# Generated by Django 5.1.1 on 2024-09-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_events_event_rename_listings_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
