# Generated by Django 5.1.1 on 2024-09-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_event_alter_event_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bands/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
